export enum NavigatorEntities {
  NOTE_EDITOR = 'NoteEditor',
  SETTINGS_INSULIN = 'InsulinSettings',
  TAG_EDITOR = 'TagEditor',
  NOTE_LIST = 'Notes',
  FOOD_PAGE = 'Food',
  CHARTS = 'Charts',
  DASHBOARD = 'Dashboard',
  PROFILE = "Profile",
  BARCODE_SCANNING = 'BarcodeScanning',
  FOOD_CARD = 'FoodCard',
  FOOD_CARD_CREATION = 'FoodCardCreation',
  FOOD_NOTE_EDITOR = 'FoodNoteEditor',
  STATISTICS = 'Statistics',
  LANGUAGE_SETTINGS = 'LanguageSettings',
}
