export enum NoteListActionType {
    CHANGE_NOTE_BY_ID = "CHANGE_NOTE_BY_ID",
    DELETE_NOTE_BY_ID = "DELETE_NOTE_BY_ID_ACTION",
    ONE_LEVEL_DEEP_MERGE = 'NOTE_ONE_LEVEL_DEEP_MERGE_ACTION',
    REPLACE = "NOTE_LIST_REPLACE",
}
