import i18n from 'i18n-js';

export default function translate() {
  i18n.translations.en = {
    ...i18n.translations.en,
    notes: 'Notes',
    today: 'Today',
    yesterday: 'Yesterday',

    january: 'january',
    february: 'february',
    march: 'march',
    april: 'april',
    may: 'may',
    june: 'june',
    jule: 'jule',
    august: 'august',
    september: 'september',
    october: 'october',
    november: 'november',
    december: 'december',

    january_capital_infinitive: 'January',
    february_capital_infinitive: 'February',
    march_capital_infinitive: 'March',
    april_capital_infinitive: 'April',
    may_capital_infinitive: 'May',
    june_capital_infinitive: 'June',
    jule_capital_infinitive: 'July',
    august_capital_infinitive: 'August',
    september_capital_infinitive: 'September',
    october_capital_infinitive: 'October',
    november_capital_infinitive: 'November',
    december_capital_infinitive: 'December',

    january_capital_short: 'Jan',
    february_capital_short: 'Feb',
    march_capital_short: 'Mar',
    april_capital_short: 'Apr',
    may_capital_short: 'May',
    june_capital_short: 'Jun',
    jule_capital_short: 'Jul',
    august_capital_short: 'Aug',
    september_capital_short: 'Sep',
    october_capital_short: 'Oct',
    november_capital_short: 'Nov',
    december_capital_short: 'Dec',

    show_more: 'Show more',
    notes_not_found: 'Notes not found... Lets write a new one!'
  };
  i18n.translations.ru = {
    ...i18n.translations.ru,
    notes: 'Записи',
    today: 'Сегодня',
    yesterday: 'Вчера',

    january: 'января',
    february: 'февраля',
    march: 'марта',
    april: 'апреля',
    may: 'мая',
    june: 'июня',
    jule: 'июля',
    august: 'августа',
    september: 'сентября',
    october: 'октября',
    november: 'ноября',
    december: 'декабря',

    january_capital_infinitive: 'Январь',
    february_capital_infinitive: 'Февраль',
    march_capital_infinitive: 'Март',
    april_capital_infinitive: 'Апрель',
    may_capital_infinitive: 'Май',
    june_capital_infinitive: 'Июнь',
    jule_capital_infinitive: 'Июль',
    august_capital_infinitive: 'Август',
    september_capital_infinitive: 'Сентябрь',
    october_capital_infinitive: 'Октябрь',
    november_capital_infinitive: 'Ноябрь',
    december_capital_infinitive: 'Декабрь',

    january_capital_short: 'Янв',
    february_capital_short: 'Фев',
    march_capital_short: 'Мар',
    april_capital_short: 'Апр',
    may_capital_short: 'Май',
    june_capital_short: 'Июн',
    jule_capital_short: 'Июл',
    august_capital_short: 'Авг',
    september_capital_short: 'Сен',
    october_capital_short: 'Окт',
    november_capital_short: 'Нояб',
    december_capital_short: 'Дек',

    show_more: 'Показать больше',
    notes_not_found: 'Записей не найдено... Давайте добавим!'
  }
} 
